---
version: 2

jobs:
  build:
    docker:
      - image: golang:1.13
    working_directory: /data
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: go mod vendor
      - run: golint -set_exit_status `go list ./... | grep -v /vendor/`
      - run: go vet
      - run: go test -cover
