---
version: 2

jobs:
  build:
    docker:
      - image: golang:1.12
    working_directory: /data
    steps:
      - checkout
      - run: go mod vendor
      - run: diff -u <(echo -n) <(gofmt -d -s .)
      - run: go vet
      - run: go test -cover
